DANS UN DICTIONNAIRE DE DONNEES , IL FAUT EVITER :
1- DONNEES CONSTANTES
2- DONNEES ELABOREES : 
    2.1 : CALCULEE (PRIX ET  QTE SONT ELEMENTAIRES DONC A
    GARDER DANS LE DD PART CONTRE TOTAL=PRIX*QTE EST CALCULEE DONC A SUPPRIMER DANS LE DD
    2.2 : DEDUITE : AGE (DEDUIT DE LA DATE DE NAISSANCE) , DATE DE NAISSANCE ( IL FAUT SUPPRIMER L'AGE )
    SI ON GARDE IL Y  A AURA DE LA REDONDANCE ,
    NOM , PRENOM ET LE COMPLET 


    LES CARDINALITES : 4
    0,1
    0,N 
    1,1
    1,N